# Constants for Filter Operations
FILTER_EXCLUDE_KEY = "FILTER_EXCLUDE_KEY"
FILTER_TYPE_LIST_KEY = "FILTER_TYPE_LIST_KEY"
FILTER_ELEMENT_TYPE_KEY = "FILTER_ELEMENT_TYPE_KEY"
FILTER_STORAGE_NAME_KEY = "FILTER_STORAGE_NAME_KEY"

FILTER_KEY_LIST = [FILTER_EXCLUDE_KEY, FILTER_TYPE_LIST_KEY, FILTER_ELEMENT_TYPE_KEY, FILTER_STORAGE_NAME_KEY]

