
MLR_P_VALUE_KEY = "MLR_P_VALUE_KEY"
TARGET_COLUMN_KEY = "the_target_column"
VARIABLE_COLUMN_KEY = "the_variable_column"
MLR_SUMMARY = "MLR_SUMMARY"
AIC_VALUE = "AIC_VALUE"
MLR_MODEL = "MLR_MODEL"
MLR_MODEL_R_SQRD = "MMLR_MODEL_R_SQRDL"

LM_PREDICTOR = 'predictor'
LM_P_VALUE = 'p-value'
LM_F_VALUE = 'f-value'
LM_F_P_VALUE = 'f p-value'
LM_LAGRANGE_MULTIPLIER_STATISTIC = 'Lagrange Multiplier Statistic'
LM_COEFFICIENT = 'coefficient'
LM_CONSTANT = 'const'
LM_FEATURE_NUM = 'feature #'
LM_STANDARD_ERROR = 'std err'
LM_T_STATISTIC = 't-statistic'
LM_LS_CONF_INT = '[0.025'
LM_RS_CONF_INT = '0.975]'
LM_VIF = 'VIF'
LM_JARQUE_BERA_STATISTIC = 'Jarque-Bera Statistic'
LM_JARQUE_BERA_PROB = 'Chi^2 two-tail prob'
LM_JB_SKEW = 'Skew'
LM_JS_KURTOSIS = 'Kurtosis'

# KNN assumptions
KNN_ACCURACY_SCORE = 'Accuracy Score'
KNN_AVERAGE_PRECISION = 'Average Precision'
KNN_F1_SCORE = 'F1 Score'
KNN_PRECISION = 'Precision'
KNN_RECALL = 'Recall'
KNN_ROC_SCORE = 'ROC Score'
KNN_Y_PRED = 'Y-Predicted'
KNN_Y_SCORES = 'Y scores'

# storage keys
LM_INITIAL_MODEL = "LM_INITIAL_MODEL"
LM_FINAL_MODEL = "LM_FINAL_MODEL"
LM_VALID_TYPES = [LM_INITIAL_MODEL, LM_FINAL_MODEL]
LM_STEP = "LM_STEP"
LM_ELIMINATED_FEATURES = "LM_ELIMINATED_FEATURES"
LF_ELIM_REASON_VIF = "VIF"
LF_ELIM_REASON_P_VALUE = "P_VALUE"

# TRAIN / TEST SPLIT keys
X_TRAIN = "X_TRAIN"
X_TEST = "X_TEST"
Y_TRAIN = "Y_TRAIN"
Y_TEST = "Y_TEST"
X_ORIGINAL = "X_ORIGINAL"



