# Key Constants
from openpyxl.styles import Font, Side
from openpyxl.styles.numbers import BUILTIN_FORMATS

REPORT_INITIAL = "INITIAL_"
REPORT_BASE_NAME = "DATASET_ANALYSIS.xlsx"
REPORT_DF_BASE_NAME = "DATAFRAME_OUTPUT.xlsx"
REPORT_ORIG_DF_TAB_NAME = "ORIGINAL DATASET"
REPORT_CLEAN_DF_TAB_NAME = "CLEANED DATASET"
REPORT_NORM_DF_TAB_NAME = "NORMALIZED"
REPORT_PAC_TAB_NAME = "PCA_LOADINGS"
BASIC_ITEM_HEADER = "COLUMN #"
BASIC_COLUMN_HEADER = "COLUMN NAME"
BASIC_TYPE_HEADER = "TYPE"
BASIC_COUNT_HEADER = "COUNT"
BASIC_SINGLE_SPACE = " "
BOOLEAN_HEADER = "BOOLEAN"
BASIC_DUPLICATE_HEADER = "DUPLICATES"
YES_NO_LIST = ["Yes", "No"]

# INTEGER PAGE KEYS
MEAN_HEADER = "MEAN"
MEDIAN_HEADER = "MEDIAN"
VARIANCE_HEADER = "VARIANCE"
STD_DEV_HEADER = "STD DEV"
SKEW_HEADER = "SKEW"
MIN_HEADER = "MIN"
MAX_HEADER = "MAX"
DISTRIBUTION = "DISTRIBUTION"
DISTRIBUTION_PARAMS = "DISTRIBUTION_PARAMS"

# FLOAT PAGE KEYS
NA_COLUMN_LABEL = "NaN COUNT"

# BOOLEAN PAGE KEYS
VALUES_UNIQUE = "UNIQUE"
VALUES_ACTUAL = "ACTUAL VALUES"
TRUE_COUNT = "COUNT OF TRUE"
FALSE_COUNT = "COUNT OF FALSE"

# OBJECT
DISTINCT_VALUE_COUNT = "# OF DISTINCT VALUES"
VALUES_TOO_MANY = "TOO MANY TO DISPLAY"
VALUE_UNIQUE_HEADER = "IS DATA UNIQUE?"
HEADER_COUNT_START = "COUNT OF ["
HEADER_COUNT_STOP = "]"
OBJ_DATA_FIELD_COLUMN_VAL = "COLUMN VALUE"
OBJ_DATA_FIELD_COUNT = "COUNT"
OBJ_DATA_FIELD_COLUMN_PCT = "COLUMN %"
OBJ_DATA_FIELD_CUM_PCT = "CUM. %"
DEFAULT_ROW_HEADER_SPACER = 2
DEFAULT_ROW_SPACER = 2
MINIMUM_OFFSET = 30

# CORRELATION
COLUMN_HEADER = "COLUMN"
CORRELATION_HEADER = "CORRELATION"
CORRELATION_LEVEL = "LEVEL"

# CHI-SQUARED
CHI_SQUARED_HEADER = "CHI-SQUARED P-VALUE"

# LINEAR MODEL
TARGET_HEADER = "TARGET"
NUMBER_OF_FEATURES_HEADER = "# OF FEATURES"
CONSTANT_HEADER = "CONSTANT"
R_SQUARED_HEADER = "R SQUARED"
PSEUDO_R_SQUARED_HEADER = "PSEUDO R SQUARED"
ADJ_R_SQUARED_HEADER = "ADJ R SQUARED"
AIC_HEADER = "AIC"
BIC_HEADER = "BIC"
VIF_HEADER = "VIF"
F_STATISTIC_HEADER = "F-STATISTIC"
P_VALUE_F_STATISTIC_HEADER = "Prob (F-statistic)"
STANDARD_ERROR_HEADER = "STD ERROR"
T_STATISTIC_HEADER = "T-STATISTIC"
FEATURE_NUMBER = "FEATURE #"
FEATURE_NAME_HEADER = "FEATURE NAME"
P_VALUE_HEADER = "P-VALUE"
COEFFICIENT_HEADER = "COEFFICIENT"
NUMBER_OF_OBS = "NUMBER OF OBSERVATIONS"
DEGREES_OF_FREEDOM_MODEL = "DEGREES OF FREEDOM (model)"
DEGREES_OF_FREEDOM_RESID = "DEGREES OF FREEDOM (residuals)"
DURBAN_WATSON_STATISTIC = "DURBAN WATSON STATISTIC"
JARQUE_BERA_STATISTIC = "JARQUE BERA STATISTIC"
LOG_LIKELIHOOD = "LOG LIKELIHOOD"
RESIDUAL_STD_ERROR = "RESIDUAL STANDARD ERROR"
BREUSCH_PAGAN_P_VALUE = "BRUESCH PAGAN P-VALUE"
MODEL_ACCURACY = "MODEL ACCURACY"
MODEL_PRECISION = "MODEL PRECISION"
MODEL_AVG_PRECISION = "MODEL AVERAGE PRECISION"
MODEL_RECALL = "MODEL RECALL"
MODEL_F1_SCORE = "MODEL F1 SCORE"
AIC_SCORE = "AIC"
BIC_SCORE = "BIC"
MODEL_CONSTANT = "CONSTANT"
MODEL_ROC_SCORE = 'ROC Score'
MODEL_BEST_SCORE = "MODEL BEST SCORE"
MODEL_BEST_PARAMS = "MODEL BEST PARAMS"
MODEL_Y_PRED = 'Y-Predicted'
MODEL_Y_SCORES = 'Y scores'
MODEL_STANDARD_ERROR = 'STD ERR'
MODEL_MEAN_ABSOLUTE_ERROR = 'MEAN ABSOLUTE ERROR'
MODEL_MEAN_SQUARED_ERROR = 'MEAN SQUARED ERROR'
MODEL_ROOT_MEAN_SQUARED_ERROR = 'ROOT MEAN SQUARED ERROR'
MODEL_R_SQUARED = 'R SQUARED'

# double border style and color = black
BORDER_DOUBLE = Side(border_style="double", color="00000000")
# thick border style and color = black
BORDER_THICK = Side(border_style="thick", color="00000000")

# format constant ##,###
FORMAT_NUMBER_COMMA = BUILTIN_FORMATS[3]
# format constant
FORMAT_PERCENTAGE = BUILTIN_FORMATS[10]

# define font
X_AXIS_FONT = Font(name='Calibri', size=6, bold=False, italic=False, vertAlign=None,
                   underline='none', strike=False, color='FF000000')
Y_AXIS_FONT = Font(name='Calibri', size=7, bold=False, italic=False, vertAlign=None,
                   underline='none', strike=False, color='FF000000')
