SAMPLE_MEAN = "mean"
SAMPLE_MODE = "mode"
SAMPLE_VARIANCE = "var"

# STATISTICS CONSTANTS
MEAN = "MEAN"
MEDIAN = "MEDIAN"
STD_DEV = "STD_DEV"
MEAN_ABS_DEV = "MEAN_ABS_DEV"
VARIANCE = "VARIANCE"
SKEW = "SKEW"
KURTOSIS = "KURTOSIS"
NAME = "NAME"
COUNT = "COUNT"

# Normal constants
NORMALITY_TEST = "NORMALITY_TEST"
NORMALITY_TEST_P_VALUE = "NORMALITY_TEST_P_VALUE"
NORMALITY_TEST_METHOD = "NORMALITY_TEST_METHOD"
NORMALITY_TEST_NOT_NORMAL = "NOT NORMAL"
NORMALITY_TEST_NORMAL = "NORMAL"

# Exponential constants
EXPONENTIAL_TEST = "EXPONENTIAL_TEST"
EXPONENTIAL_TEST_P_VALUE = "EXPONENTIAL_TEST_P_VALUE"
EXPONENTIAL_TEST_METHOD = "EXPONENTIAL_TEST_METHOD"
EXPONENTIAL_TEST_NOT_EXP = "NOT EXPONENTIAL"
EXPONENTIAL_TEST_EXP = "EXPONENTIAL"

# test names
KOLMOGOROV_SMIRNOV_TEST = "Kolmogorov-Smirnov"
SHAPIRO_WILKS_NORMALITY_TEST = "Shapiro-Wilks"

STAT_OPTIONS = [MEAN, MEDIAN, STD_DEV, MEAN_ABS_DEV, VARIANCE, SKEW, KURTOSIS, NAME, COUNT, NORMALITY_TEST,
                NORMALITY_TEST_P_VALUE, NORMALITY_TEST_METHOD]

# key constants
CORR_KEY = "CORR_KEY"
CORR_EXCEED_LEVEL = "CORR_EXCEED_LEVEL"
ALL_CORRELATIONS = "ALL_CORRELATIONS"
DIST_NAME = "DIST_NAME"
DIST_PARAMETERS = "DIST_PARAMETERS"


